"""Add ratings and type to recipes

Revision ID: 70477bb9c4ae
Revises: a1b0d4e4033c
Create Date: 2024-09-11 03:18:38.351485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70477bb9c4ae'
down_revision = 'a1b0d4e4033c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Enum('SNACK', 'ENTREE', 'DESSERT', 'LUNCH', name='recipetype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###
