"""Add reviews table

Revision ID: 24f5501d8695
Revises: 8dcecc6748e1
Create Date: 2024-09-13 17:15:22.149411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f5501d8695'
down_revision = '8dcecc6748e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('ratings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratings', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
