"""Added image field to recipes, big oversight on my part

Revision ID: 4b064a50e460
Revises: 3f23b854a66c
Create Date: 2024-09-14 18:36:25.577348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b064a50e460'
down_revision = '3f23b854a66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
